general {
    lock_cmd = akatsuki-system-lock                         # lock screen and 1password
    before_sleep_cmd = AKATSUKI_LOCK_ONLY=true akatsuki-system-lock    # lock before suspend without scheduling display off.
    after_sleep_cmd = sleep 1 && akatsuki-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

# Start screensaver after 10 minutes
listener {
    timeout = 600
    on-timeout = pidof hyprlock || akatsuki-launch-screensaver
}

# Lock system after 10 minutes + 2s margin
listener {
    timeout = 602
    on-timeout = akatsuki-system-lock
    on-resume = akatsuki-system-wake
}
